### ISSUE TITLE
该删除node_modules

### ISSUE THREAD

**Issue by Surile** [Alalabu/calendar2#1]
不应该把node_modules上传上来吧。

你应该是在创建`.gitignore `之前就已经把node_modules加入到暂存区中了。

```javascipt
git rm --cache node_modules
```

**Comment by Alalabu** [comment]
> 不应该把node_modules上传上来吧。
> 
> 你应该是在创建`.gitignore `之前就已经把node_modules加入到暂存区中了。
> 
> ```
> git rm --cache node_modules
> ```

谢谢，大意了 ：0

**Comment by Surile** [comment]
> > 不应该把node_modules上传上来吧。
> > 你应该是在创建`.gitignore `之前就已经把node_modules加入到暂存区中了。
> > ```
> > git rm --cache node_modules
> > ```
> 
> 谢谢，大意了 ：0

太大意了
